import logging
import uuid
from typing import List, Dict, Any
from qdrant_client.http.models import Distance, VectorParams, PointStruct, Filter, FieldCondition, MatchValue
from .qdrant_service import get_qdrant_client, collection_exists, create_collection

logger = logging.getLogger(__name__)

class QdrantDocumentService:
    def __init__(self):
        self.client = get_qdrant_client()
        self.collection_name = "uploaded_documents"
        # 384 is the size of embeddings generated by BAAI/bge-small-en-v1.5
        create_collection(self.client, self.collection_name, vector_size=384)

    def index_document_chunks(
        self,
        tenant_id: int,
        user_id: int,
        file_id: int,
        filename: str,
        file_type: str,
        chunks: List[str],
        vectors: List[List[float]],
        chunk_metadatas: List[Dict[str, Any]] = None
    ):
        """
        Indexes text chunks and their embeddings into the Qdrant database.
        """
        points = []
        for i, (chunk_text, vector) in enumerate(zip(chunks, vectors)):
            point_id = str(uuid.uuid4())
            payload = {
                "tenant_id": tenant_id,
                "user_id": user_id,
                "file_id": file_id,
                "filename": filename,
                "file_type": file_type,
                "text": chunk_text,
                "chunk_index": i
            }
            if chunk_metadatas and i < len(chunk_metadatas):
                payload.update(chunk_metadatas[i])

            points.append(
                PointStruct(
                    id=point_id,
                    vector=vector,
                    payload=payload
                )
            )

        # Batch upsert points
        self.client.upsert(
            collection_name=self.collection_name,
            wait=True,
            points=points
        )
        logger.info(f"Indexed {len(points)} chunks for file_id {file_id} into collection '{self.collection_name}'.")

    def search_relevant_chunks(
        self,
        tenant_id: int,
        user_id: int,
        query_vector: List[float],
        limit: int = 5
    ) -> List[Dict[str, Any]]:
        """
        Searches the vector DB for chunks matching the query.
        Filters by tenant_id and user_id to ensure strict data privacy.
        """
        try:
            search_result = self.client.query_points(
                collection_name=self.collection_name,
                query=query_vector,
                query_filter=Filter(
                    must=[
                        FieldCondition(key="tenant_id", match=MatchValue(value=tenant_id)),
                        FieldCondition(key="user_id", match=MatchValue(value=user_id))
                    ]
                ),
                limit=limit
            )
            return [
                {
                    "text": hit.payload.get("text", ""),
                    "score": hit.score,
                    "filename": hit.payload.get("filename", ""),
                    "file_type": hit.payload.get("file_type", ""),
                    "metadata": hit.payload
                }
                for hit in search_result.points
            ]
        except Exception as e:
            logger.error(f"Error searching Qdrant documents: {e}")
            return []

    def delete_file_chunks(self, file_id: int):
        """
        Deletes all chunks associated with a specific file from Qdrant.
        """
        try:
            self.client.delete(
                collection_name=self.collection_name,
                points_selector=Filter(
                    must=[
                        FieldCondition(key="file_id", match=MatchValue(value=file_id))
                    ]
                )
            )
            logger.info(f"Deleted Qdrant points for file_id {file_id}")
        except Exception as e:
            logger.error(f"Failed to delete Qdrant points for file_id {file_id}: {e}")
            raise

_qdrant_doc_service = None

def get_qdrant_doc_service() -> QdrantDocumentService:
    global _qdrant_doc_service
    if _qdrant_doc_service is None:
        _qdrant_doc_service = QdrantDocumentService()
    return _qdrant_doc_service

